const WH_EVENT = {
    COMMON: {
        NEW_BLOCK: 'NEW_BLOCK',
        CONFIRMED_TX: 'CONFIRMED_TX',
        ADDRESS: 'ADDRESS',
        TRANSACTION_CONFIRMATIONS: 'TRANSACTION_CONFIRMATIONS',
    },
    ETH: {
        TOKEN: 'TOKEN',
        TXPOOL: 'TXPOOL',
    },
    ETC: {
        TXPOOL: 'TXPOOL',
    },
    OMNI: {
        OMNI_CONFIRMED_TX: 'OMNI_CONFIRMED_TX',
        OMNI_TRANSACTION_CONFIRMATIONS: 'OMNI_TRANSACTION_CONFIRMATIONS',
        OMNI_TOKEN: 'OMNI_TOKEN',
    }
};

module.exports = {
    WH_EVENT: WH_EVENT,
};
